---
- hosts: ci
  remote_user: ovh
  roles:
    - security
    - git
    - mysql
    - php
    - node
    - nginx
    - { role: jenkins, tags: ['jenkins'] }
    - { role: sonarqube, tags: ['sonar'] }
    - goorelease
